# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    image: se-golang-api
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: example
      DB_HOST: db 
      DB_PORT: 5432 
      DB_NAME: api
    ports:
      - 8000:8000 
    links:
      - "db:database"